{% set name = "flask-smorest" %}
{% set version = "0.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dac718229ca5de603c5aa59b391454b7ed81d72fa2adf1f69247d1eb60f68f50

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - apispec >=3
    - flask >=1.1
    - marshmallow >=2.15.2
    - python >=3
    - webargs >=6
    - werkzeug >=0.15

test:
  imports:
    - flask_smorest

about:
  home: https://github.com/marshmallow-code/flask-smorest
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: DB agnostic framework to build auto-documented REST APIs with Flask and marshmallow
  doc_url: https://flask-smorest.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/flask-smorest

extra:
  recipe-maintainers:
    - mcs07
